name: Build container images each Sunday

on:
  schedule:
   - cron: "0 0 * * 0"

env:
  DOCKER_BUILDKIT: 1
  REGISTRY_IMAGE: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"

jobs:
  build:
    strategy:
      matrix:
        image: [debootstrapper, archer]
        arch: [amd64]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: image/${{ matrix.arch }}/${{ matrix.image }}
          pull: true
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}/${{ matrix.image }}/${{ matrix.arch }}:latest
